# Generated by Django 3.0.2 on 2020-01-14 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
